### ISSUE TITLE
Composer.json is wrong

### ISSUE THREAD

**Issue by lichunqiang** [cn/GB2260.php#1]
```
"autoload": {
        "psr-4": { "": "src/" }
    }
```

**Comment by shen2** [comment]
好像没啥问题啊。这样写是合法的。

**Comment by lichunqiang** [comment]
写法是合法 -- ！
但是通过composer安装后就不能用。

这是 composer生成的 

```
'' => array($vendorDir . '/cn/gb2260/src'),
```

这么配置会去目录下的src下找

**Comment by bcho** [comment]
@lichunqiang 直接用 `use GB2260;` 不行吗？ 不过我也建议加一个 namespace ，避免污染下游的命名空间。

**Comment by lichunqiang** [comment]
不行的 。。。
看composer配置

**Comment by shen2** [comment]
问题已经解决了。你们更新一下最新版。

**Comment by bcho** [comment]
@shen2 为啥不用个 `Cn` 的 namespace？

**Comment by shen2** [comment]
@bcho 是个好建议，已经加了。
https://github.com/cn/GB2260.php/commit/317f7271d8b95e67482248aec289e4c5e41a6e96

**Comment by lichunqiang** [comment]
刷新下 package list 吧

**Comment by shen2** [comment]
@lichunqiang 已经更新

**Comment by lichunqiang** [comment]
啥情况，packagelist上的commit还是第一次commit的呢

https://packagist.org/packages/cn/gb2260

**Comment by shen2** [comment]
现在已经更新了。

**Comment by lichunqiang** [comment]
ok了

要是能打个tag就好了
